language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

services: rabbitmq

before_script:
  - composer install -n
  - app/console sonata:notification:start > /dev/null &

script: phpunit -c app
